language: python
sudo: required

install:
  - docker-compose build
  - docker-compose up -d
script:
  - docker-compose exec exporter pytest
services:
  - docker

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
