language: python
sudo: required

install:
  - docker-compose build
script:
  - docker-compose run --rm exporter pytest
services:
  - docker

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
